dist: trusty
group: beta
language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
before_install:
- if [ -d node_modules ] && [ x$(cat node_modules/.last-node-version 2>/dev/null) != x$(node -e 'console.log(process.version)') ]; then npm rebuild --update-binary && node -e 'console.log(process.version)' > node_modules/.last-node-version; fi
before_script:
- npm run build
deploy:
  provider: npm
  email: npm@collaborne.com
  api_key:
    secure: "FowUY352AGC42+3ESXEAcRyfSuZovfoV0DlMFek+tp3zXJu4pak/RvMoDFz49siL1O1MP9xMn2a2injFYxynUgQMcgBuBJJM4FhI+Ls39TBfIwHFhZdCuONraTtSDgWxMWh+Knad4oqhZpfq7JzS2N84fPSNboghwKCP8Ek2e4BhXgbG/haMOHA6V1Y27Rfml/CV3LBrbQywm4egRxQLmVbMe8Sgj8OBdBnbegLmkTDpwc0F/FAmmIOBSP/SAnRmUIetGppauaGWEUW0r6bseWal/oqXdtrJaJPC4csYZUcic55/Hh4ZEmfw5hXnKKhEaaQs4sUuWiYq/rm9/a6kjWThCih/j6Yv4cQxK7zN9VdglRyw9stDEFnbaUFPoNvm5D4t9O4XafvaS5mVCgc1OHLpp6St+AXiHk4S4kquid5AAgDfl8A/xO0LjrPOlAzthuVE7QRJh/ibSbdjABZ+6FpHjwBTBSm/HJxMtyZG5M2Vek7xp6+ATkkOnGqNZjXZWH2nKIgdHpQgU6DIzmpYqqp9/pEzpP2cIvvsozpTw0bfaJA65PVEWb8Cw6K6EGpEFd0LMEqZKbBmf4CyRn23Zm3o5h16nyrFgSy7wx6rnGbcB9Wpt2/UYZy2535Exi55qPsAU3uT2HSL5zkMCX0rG1czaLl8h7koW5kV5oZU70k="
  on:
    tags: true
    condition: $(node -e 'console.log("v" + require("./package.json").version)') = ${TRAVIS_TAG}
  skip_cleanup: true
